#!/usr/bin/env python3
"""
SIGN-gate variant of run_unified_protocol.py (verifier flipped, nothing else).
Generated by textual substitution from run_unified_protocol.py so that the ONLY
difference from the unified_protocol baseline is the acceptance rule.
Arm dir: sign_banded_unified.  Usage: python -u run_sign_banded_unified.py --anchor seed1
"""
import sys,os,json,time,hashlib,argparse
import numpy as np
PROJECT_DIR=os.path.dirname(os.path.abspath(__file__));PARENT_DIR=os.path.dirname(PROJECT_DIR)
sys.path.insert(0,PROJECT_DIR);sys.path.insert(0,PARENT_DIR)
os.environ.setdefault('KMP_DUPLICATE_LIB_OK','TRUE');os.environ['LUMOPT_BACKEND']='2026'
if hasattr(sys.stdout,'reconfigure'):sys.stdout.reconfigure(line_buffering=True)
from config import RESULTS_BASE,ANCHORS,DEFAULT_K,RNG_BASE_SEED,PATCH_SIZES,PATCH_TYPES
from shared import load_jac_npz,Trajectory
from shared.index_utils import flat_to_col,flat_to_row,N_COLS,N_ROWS,get_top_k_indices,apply_mask_to_field
from strategies import _global_patch_scan
from run_pilot import Session,compute_scaled_threshold
from budget import BudgetLedger
from metadata import make_metadata

BUDGET=200;WARMUP_MAX=50;WARMUP_MIN=5;PROBE_N=20;CK=20
BANDS=[(51,200),(201,500),(501,1000),(1000,99999)];SG='spatial'
ACCEPT_TYPES={'wu_a','probe_a','bb_a','bs_a'}

def _h(i):return hashlib.md5(','.join(str(x) for x in sorted(i)).encode()).hexdigest()[:12]
def _am(i,mz):
    for idx in i:
        c=flat_to_col(idx)
        for lo,hi in mz:
            if lo<=c<=hi:return True
    return False

def build_strata(anchor,diag):
    m=diag['mask'];v=diag.get('variant','conj_a');p=ANCHORS[anchor]['port']
    jd=os.path.join(PARENT_DIR,'wdm3_3d','results_3d','jac3d')
    jp=os.path.join(jd,f'jac_{anchor}_P{p}@1550nm_g0.npz')
    if not os.path.exists(jp):jp=os.path.join(jd,f'jac_{anchor}_P{p}@1550nm.npz')
    jac=load_jac_npz(jp);g=jac.get(f'gain_{v}',jac['gain_raw'])
    import config as _c;_c.PATCH_SIZES=PATCH_SIZES;_c.PATCH_TYPES=PATCH_TYPES
    ap=_global_patch_scan(np.abs(g),gain_raw=g)
    sc=[]
    for pp in ap:
        if _am(pp['indices'],m):continue
        gs=sum(abs(float(g[flat_to_col(i),flat_to_row(i)])) for i in pp['indices'] if 0<=flat_to_col(i)<N_COLS and 0<=flat_to_row(i)<N_ROWS)
        if gs<=0:continue
        sc.append({'hash':_h(pp['indices']),'indices':pp['indices'],'n':len(pp['indices']),'size':pp['size'],'score':gs})
    sc.sort(key=lambda x:x['score'],reverse=True)
    for i,s in enumerate(sc):s['rank']=i+1
    st={}
    for lo,hi in BANDS:st[f'band_{lo}_{hi}']=[s for s in sc if lo<=s.get('rank',0)<=hi]
    st[SG]=[];return st

def gen_spatial(n,cp,rng):
    qs=[(0,40,0,50),(40,80,0,50),(0,40,50,100),(40,80,50,100)]
    nq=max(1,n//4);seen=set();pts=[]
    for cl,ch,rl,rh in qs:
        cnt=0;att=0
        while cnt<nq and att<nq*30:
            att+=1;sz=int(rng.choice([3,4,5]))
            cm=max(cl,min(ch-sz,N_COLS-sz));rm=max(rl,min(rh-sz,N_ROWS-sz))
            if cm<=cl or rm<=rl:continue
            ci=int(rng.integers(cl,cm+1) if cm>cl else cl)
            ri=int(rng.integers(rl,rm+1) if rm>rl else rl)
            if ci+sz>N_COLS or ri+sz>N_ROWS:continue
            idxs=[];ov=False
            for di in range(sz):
                for dj in range(sz):
                    ix=(ci+di)*N_ROWS+(ri+dj)
                    if ix in cp:ov=True;break
                    idxs.append(ix)
                if ov:break
            if ov or not idxs:continue
            h=_h(idxs)
            if h in seen:continue
            seen.add(h);pts.append({'hash':h,'indices':sorted(idxs),'size':sz,'n':len(idxs),'score':float('nan')});cnt+=1
    return pts[:n]

def try_accept(s,idx,dg,ld,tr,z=2.0):
    n=len(idx);th=0.0  # SIGN GATE: flipped from compute_scaled_threshold (the ONLY protocol change)
    dF=s.try_patch(idx)
    ld.charge('candidate_reject',n=1);tr.eval_count=ld.eval_count
    if dF>th:
        if not ld.is_exhausted():
            s.commit_patch(idx);ld.charge('patch_accept',n=1);tr.eval_count=ld.eval_count;tr.cumulative_dJ+=dF;return dF,True,th
    return dF,False,th

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--anchor',required=True);parser.add_argument('--max-exec-eval',type=int,default=None);args=parser.parse_args()
    anchor=args.anchor;t0=time.time();rng=np.random.default_rng(RNG_BASE_SEED)
    arm_dir=os.path.join(RESULTS_BASE,'final_rerun_2026_08_13_protocol_v2',anchor,'sign_banded_unified',f'budget{BUDGET}','repeat0')
    os.makedirs(arm_dir,exist_ok=True);cp=os.path.join(arm_dir,'ckpt.json')
    print(f'SIGN-band variant of unified protocol: {anchor}')
    with open(os.path.join(RESULTS_BASE,'shared',anchor,'diagnosis.json')) as f:diag=json.load(f)
    diag['threshold_single']=diag.get('threshold_single',diag['sigma_single']*2)
    C=diag.get('C',0);mu=diag.get('mu_single',0)
    print(f'C={C:.2f} mu={mu:+.2e}')
    strata=build_strata(anchor,diag)
    port=ANCHORS[anchor]['port']
    jd=os.path.join(PARENT_DIR,'wdm3_3d','results_3d','jac3d')
    jp=os.path.join(jd,f'jac_{anchor}_P{port}@1550nm_g0.npz')
    if not os.path.exists(jp):jp=os.path.join(jd,f'jac_{anchor}_P{port}@1550nm.npz')
    import lum_backend,_lumopt_compat
    ledger=BudgetLedger(total_budget=BUDGET);traj=Trajectory('sign_banded_unified',anchor,BUDGET,0)
    committed=set();tested=set()
    if os.path.exists(cp):
        with open(cp) as f:ck=json.load(f)
        committed=set(ck['committed_pixels']);tested=set(ck['tested_hashes'])
        traj.steps=ck['trajectory_steps'];traj.cumulative_dJ=ck['trajectory_cumulative_dJ']
        traj.eval_count=ck['trajectory_eval_count'];ledger=BudgetLedger.from_dict(ck['ledger'])
        ec_resume = ck.get('eval_counter', 0)
        bi_resume = ck.get('band_idx', 0)
        print(f'[RESUME] eval={ec_resume}')
    else:
        # === Warmup + Probe in ONE Session ===
        with Session(anchor,tag='wu') as s:
            jac=load_jac_npz(jp);gn=jac['gain_raw'];pool=set();ac=0
            while not ledger.is_exhausted() and ac<WARMUP_MIN and ledger.eval_count<WARMUP_MAX:
                mk=apply_mask_to_field(gn.copy(),[])
                for idx in pool:mk[flat_to_col(idx),flat_to_row(idx)]=-float('inf')
                cs=get_top_k_indices(mk,DEFAULT_K)
                if not cs:break
                for idx in cs:
                    if ledger.is_exhausted() or ac>=WARMUP_MIN:break
                    if idx in pool:continue
                    dF,ok=s.try_single(idx,threshold=0.0);pool.add(idx)  # SIGN GATE
                    ledger.charge('candidate_accept' if ok else 'candidate_reject',n=1);traj.eval_count=ledger.eval_count
                    if ok:ac+=1;traj.cumulative_dJ+=dF;traj.record_step({'type':'wu_a','idx':idx,'dJ':dF})
                    else:traj.record_step({'type':'wu_r','idx':idx,'dJ':dF})
            committed={s['idx'] for s in traj.steps if s.get('type')=='wu_a'}
            for step in traj.steps:
                il=[step['idx']] if 'idx' in step else step.get('indices',[])
                if il:tested.add(_h(il))
            print(f'Warmup: {ledger.eval_count}e {len(committed)}a dJ={traj.cumulative_dJ:+.4e}')
            # Probe: 20 valid patch evals — STILL INSIDE Session
            keys=list(strata.keys());ki=0;cursor={k:0 for k in keys}
            apool={k:([c for c in strata[k] if c['hash'] not in tested] if k!=SG else None) for k in keys}
            pv=0
            while pv<PROBE_N and not ledger.is_exhausted():
                k=keys[ki%len(keys)];ki+=1
                if k==SG:
                    pts=gen_spatial(1,committed,rng)
                    if pts:c=pts[0]
                    else:continue
                else:
                    pool=apool[k];found=False
                    while cursor[k]<len(pool):
                        c=pool[cursor[k]];cursor[k]+=1
                        if c['hash'] in tested:continue
                        if any(p in committed for p in c['indices']):continue
                        found=True;break
                    if not found:continue
                h=c['hash']
                if h in tested:continue
                if any(p in committed for p in c['indices']):continue
                tested.add(h);dF,ok,_=try_accept(s,c['indices'],diag,ledger,traj);pv+=1
                if ok:committed.update(c['indices']);traj.record_step({'type':'probe_a','indices':c['indices'],'dJ':dF})
                else:traj.record_step({'type':'probe_r','indices':c['indices'],'dJ':dF})
            print(f'Probe: {pv}e')
        # Session closed after probe

    # === Banded execution in NEW Session ===
    rem=ledger.remaining();print(f'Banded: {rem}e')
    with Session(anchor,tag='ex') as s:
        if os.path.exists(cp) and committed:
            for step in traj.steps:
                if step.get('type','') not in ACCEPT_TYPES:continue
                if 'indices' in step:s.commit_patch(step['indices'])
                elif 'idx' in step:s.try_single(step['idx'],threshold=-float('inf'))
            print('[RESUME] geometry rebuilt')
        bk=[k for k in strata if k!=SG]
        bi = bi_resume if os.path.exists(cp) else 0
        ec = ec_resume if os.path.exists(cp) else 0
        while not ledger.is_exhausted() and (args.max_exec_eval is None or ec < args.max_exec_eval):
            if ec>0 and ec%4==0:
                pts=gen_spatial(1,committed,np.random.default_rng(RNG_BASE_SEED+ec))
                if pts:
                    p=pts[0]
                    if p['hash'] not in tested:
                        tested.add(p['hash']);dF,ok,_=try_accept(s,p['indices'],diag,ledger,traj)
                        if ok:committed.update(p['indices']);traj.record_step({'type':'bs_a','indices':p['indices'],'dJ':dF})
                        else:traj.record_step({'type':'bs_r','indices':p['indices'],'dJ':dF})
                        ec+=1;continue
            key=bk[bi%len(bk)];bi+=1;cands=strata.get(key,[])
            avail=[c for c in cands if c['hash'] not in tested and not any(p in committed for p in c['indices'])]
            if not avail:continue
            c=avail[0];tested.add(c['hash'])
            dF,ok,_=try_accept(s,c['indices'],diag,ledger,traj)
            if ok:committed.update(c['indices']);traj.record_step({'type':'bb_a','indices':c['indices'],'dJ':dF,'group':key})
            else:traj.record_step({'type':'bb_r','indices':c['indices'],'dJ':dF,'group':key})
            ec+=1
            if ec%CK==0:
                na=sum(1 for st in traj.steps if st.get('type','') in ACCEPT_TYPES)
                with open(cp,'w') as f:json.dump({'trajectory_steps':traj.steps,'trajectory_cumulative_dJ':traj.cumulative_dJ,'trajectory_eval_count':traj.eval_count,'ledger':ledger.to_dict(),'committed_pixels':list(committed),'tested_hashes':list(tested),'eval_counter':ec,'band_idx':bi},f)
                print(f'  eval={ec} a={na} dJ={traj.cumulative_dJ:+.6e} left={ledger.remaining()}',flush=True)
    if args.max_exec_eval is not None and ec >= args.max_exec_eval and not ledger.is_exhausted():
        # max-exec-eval hit: save ckpt and write trajectory (for the resume-equivalence
        na=sum(1 for st in traj.steps if st.get('type','') in ACCEPT_TYPES)
        with open(cp,'w') as f:json.dump({'trajectory_steps':traj.steps,'trajectory_cumulative_dJ':traj.cumulative_dJ,'trajectory_eval_count':traj.eval_count,'ledger':ledger.to_dict(),'committed_pixels':list(committed),'tested_hashes':list(tested),'eval_counter':ec,'band_idx':bi},f)
        traj.to_json(os.path.join(arm_dir,'trajectory.json'))
        print(f'[STOP] max-exec-eval={args.max_exec_eval} reached, ckpt saved for resume')
        return
    online=traj.cumulative_dJ;na=sum(1 for st in traj.steps if st.get('type','') in ACCEPT_TYPES)
    traj.to_json(os.path.join(arm_dir,'trajectory.json'))
    with open(os.path.join(arm_dir,'result.json'),'w') as f:json.dump({'experiment':'sign_banded_unified','anchor':anchor,'budget':BUDGET,'online_final_dJ':float(online),'eval_spent':ledger.eval_count,'accepts':na,'wall_clock_s':time.time()-t0,'metadata':make_metadata(__file__, 'sign_gate', 'banded')},f,indent=2)
    if os.path.exists(cp):os.remove(cp)
    print(f'DONE: online={online:+.6e} accepts={na} wall={time.time()-t0:.0f}s')

if __name__=='__main__':main()
